// <auto-generated />
using System;
using BloggerBazar.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BloggerBazar.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BloggerBazarDbContext))]
    [Migration("20260727134658_AddBusinessWebsiteAndPaymentExpiry")]
    partial class AddBusinessWebsiteAndPaymentExpiry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BloggerBazar.Domain.Entities.BloggerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int?>("AverageReach")
                        .HasColumnType("integer");

                    b.Property<bool>("BarterEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.PrimitiveCollection<string[]>("Categories")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<decimal?>("EngagementRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Gender")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("IntegrationPrice")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPromoted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("PostPrice")
                        .HasColumnType("integer");

                    b.Property<int?>("PriceFrom")
                        .HasColumnType("integer");

                    b.Property<string>("PriceNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("PriceTo")
                        .HasColumnType("integer");

                    b.Property<int?>("ReelsPrice")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("StoriesPrice")
                        .HasColumnType("integer");

                    b.Property<string>("Subcategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_user_id");

                    b.Property<int>("TotalFollowers")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("IsPromoted");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.HasIndex("Status", "City");

                    b.ToTable("blogger_profiles", (string)null);
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.BusinessProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_user_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("business_profiles", (string)null);
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("BudgetFrom")
                        .HasColumnType("integer");

                    b.Property<int?>("BudgetTo")
                        .HasColumnType("integer");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Categories")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("City")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<bool>("IsPromoted")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string[]>("Requirements")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("Status", "IsPromoted");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.CampaignApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BloggerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BloggerId", "Status");

                    b.HasIndex("CampaignId", "BloggerId")
                        .IsUnique();

                    b.ToTable("campaign_applications", (string)null);
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.CollaborationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BloggerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BloggerId", "Status");

                    b.HasIndex("BusinessId", "Status");

                    b.ToTable("collaboration_requests", (string)null);
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.ContactUnlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PaymentOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UnlockedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ViewerTelegramUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PaymentOrderId")
                        .IsUnique();

                    b.HasIndex("ViewerTelegramUserId", "TargetType", "TargetId")
                        .IsUnique();

                    b.ToTable("contact_unlocks", (string)null);
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.CreditAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Balance")
                        .HasColumnType("integer");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("credit_accounts", (string)null);
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.CreditLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId");

                    b.ToTable("credit_ledger_entries", (string)null);
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.Deal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BloggerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CampaignApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CollaborationRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CampaignApplicationId")
                        .IsUnique()
                        .HasFilter("\"CampaignApplicationId\" IS NOT NULL");

                    b.HasIndex("CollaborationRequestId")
                        .IsUnique()
                        .HasFilter("\"CollaborationRequestId\" IS NOT NULL");

                    b.HasIndex("BloggerId", "Status");

                    b.HasIndex("BusinessId", "Status");

                    b.ToTable("deals", (string)null);
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.PaymentOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AmountUzs")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PayerTelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderTransactionId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProviderTransactionId")
                        .IsUnique()
                        .HasFilter("\"ProviderTransactionId\" IS NOT NULL");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("PayerTelegramUserId", "Status");

                    b.HasIndex("Status", "ExpiresAtUtc");

                    b.HasIndex("PayerTelegramUserId", "TargetType", "TargetId")
                        .IsUnique()
                        .HasDatabaseName("IX_payment_orders_pending_contact_unlock")
                        .HasFilter("\"Status\" = 0");

                    b.ToTable("payment_orders", (string)null);
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.PortfolioItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BloggerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("BloggerId", "CreatedAtUtc");

                    b.ToTable("portfolio_items", (string)null);
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BloggerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DealId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<long>("ReviewerTelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BloggerId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("DealId", "ReviewerTelegramUserId")
                        .IsUnique();

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.SocialPlatform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BloggerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Followers")
                        .HasColumnType("integer");

                    b.Property<string>("ScreenshotUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("BloggerId");

                    b.ToTable("social_platforms", (string)null);
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.Campaign", b =>
                {
                    b.HasOne("BloggerBazar.Domain.Entities.BusinessProfile", "Business")
                        .WithMany("Campaigns")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.CampaignApplication", b =>
                {
                    b.HasOne("BloggerBazar.Domain.Entities.BloggerProfile", "Blogger")
                        .WithMany("CampaignApplications")
                        .HasForeignKey("BloggerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloggerBazar.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Applications")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blogger");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.CollaborationRequest", b =>
                {
                    b.HasOne("BloggerBazar.Domain.Entities.BloggerProfile", "Blogger")
                        .WithMany("IncomingRequests")
                        .HasForeignKey("BloggerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloggerBazar.Domain.Entities.BusinessProfile", "Business")
                        .WithMany("CollaborationRequests")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blogger");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.ContactUnlock", b =>
                {
                    b.HasOne("BloggerBazar.Domain.Entities.PaymentOrder", "PaymentOrder")
                        .WithOne("ContactUnlock")
                        .HasForeignKey("BloggerBazar.Domain.Entities.ContactUnlock", "PaymentOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaymentOrder");
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.CreditLedgerEntry", b =>
                {
                    b.HasOne("BloggerBazar.Domain.Entities.CreditAccount", "Account")
                        .WithMany("LedgerEntries")
                        .HasForeignKey("TelegramUserId")
                        .HasPrincipalKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.Deal", b =>
                {
                    b.HasOne("BloggerBazar.Domain.Entities.BloggerProfile", "Blogger")
                        .WithMany("Deals")
                        .HasForeignKey("BloggerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BloggerBazar.Domain.Entities.BusinessProfile", "Business")
                        .WithMany("Deals")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BloggerBazar.Domain.Entities.CampaignApplication", "CampaignApplication")
                        .WithOne("Deal")
                        .HasForeignKey("BloggerBazar.Domain.Entities.Deal", "CampaignApplicationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BloggerBazar.Domain.Entities.CollaborationRequest", "CollaborationRequest")
                        .WithOne("Deal")
                        .HasForeignKey("BloggerBazar.Domain.Entities.Deal", "CollaborationRequestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Blogger");

                    b.Navigation("Business");

                    b.Navigation("CampaignApplication");

                    b.Navigation("CollaborationRequest");
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.PortfolioItem", b =>
                {
                    b.HasOne("BloggerBazar.Domain.Entities.BloggerProfile", "Blogger")
                        .WithMany("PortfolioItems")
                        .HasForeignKey("BloggerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blogger");
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.Review", b =>
                {
                    b.HasOne("BloggerBazar.Domain.Entities.BloggerProfile", "Blogger")
                        .WithMany("Reviews")
                        .HasForeignKey("BloggerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BloggerBazar.Domain.Entities.BusinessProfile", "Business")
                        .WithMany("Reviews")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BloggerBazar.Domain.Entities.Deal", "Deal")
                        .WithMany("Reviews")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blogger");

                    b.Navigation("Business");

                    b.Navigation("Deal");
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.SocialPlatform", b =>
                {
                    b.HasOne("BloggerBazar.Domain.Entities.BloggerProfile", "Blogger")
                        .WithMany("Platforms")
                        .HasForeignKey("BloggerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blogger");
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.BloggerProfile", b =>
                {
                    b.Navigation("CampaignApplications");

                    b.Navigation("Deals");

                    b.Navigation("IncomingRequests");

                    b.Navigation("Platforms");

                    b.Navigation("PortfolioItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.BusinessProfile", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("CollaborationRequests");

                    b.Navigation("Deals");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.CampaignApplication", b =>
                {
                    b.Navigation("Deal");
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.CollaborationRequest", b =>
                {
                    b.Navigation("Deal");
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.CreditAccount", b =>
                {
                    b.Navigation("LedgerEntries");
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.Deal", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BloggerBazar.Domain.Entities.PaymentOrder", b =>
                {
                    b.Navigation("ContactUnlock");
                });
#pragma warning restore 612, 618
        }
    }
}
