// <auto-generated />
using BloggerBazar.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BloggerBazar.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BloggerBazarDbContext))]
    [Migration("20260731120000_AddFavorites")]
    partial class AddFavorites
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            new BloggerBazarDbContextModelSnapshot().BuildMigrationTargetModel(modelBuilder);
        }
    }
}
