namespace BloggerBazar.Api.Contracts.Bloggers;

public sealed record CreateBloggerProfileRequest(
    string Name,
    string? LastName,
    string? Username,
    string City,
    IReadOnlyCollection<string> Categories,
    string? Bio,
    string? AvatarUrl,
    string? Phone,
    string? Email,
    int TotalFollowers,
    int? AverageReach,
    decimal? EngagementRate,
    int? StoriesPrice,
    int? ReelsPrice,
    int? PostPrice,
    int? IntegrationPrice,
    bool BarterEnabled,
    IReadOnlyCollection<CreatePortfolioItemRequest>? PortfolioItems,
    string? CoverUrl = null,
    int? Age = null,
    string? Gender = null,
    string? Language = null,
    string? Subcategory = null,
    int? PriceFrom = null,
    int? PriceTo = null,
    string? PriceNote = null,
    IReadOnlyCollection<CreateSocialPlatformRequest>? Platforms = null);
