import { useEffect, useMemo, useState } from "react";
import { getBloggers, getCategories, type BloggerSearchFilters } from "../api/marketplace";
import { BloggerCard, type BloggerCardData } from "../components/BloggerCard";
import { BottomNav, Button, Chip, EmptyState, Icon, SearchBar, Skeleton } from "../components/ui";
import { categoryLabel, cityLabel, useI18n } from "../i18n";
import { uzbekistanRegions } from "../lib/taxonomy";

export function BloggerSearch() {
  const { t } = useI18n();
  const categoryFromHash = useMemo(() => new URLSearchParams(window.location.hash.split("?")[1] ?? "").get("category") ?? "", []);
  const [bloggers, setBloggers] = useState<BloggerCardData[]>([]); const [categories, setCategories] = useState<string[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [failed, setFailed] = useState(false); const [filtersOpen, setFiltersOpen] = useState(false); const [filters, setFilters] = useState<BloggerSearchFilters>({ category: categoryFromHash, sort: "popular", pageSize: 20 });
  const load = () => { setLoading(true); setFailed(false); getBloggers(filters).then((result) => { setBloggers(result.bloggers); setTotal(result.total); }).catch(() => setFailed(true)).finally(() => setLoading(false)); };
  useEffect(() => { getCategories().then(setCategories).catch(() => undefined); }, []);
  useEffect(() => { const timer = window.setTimeout(load, 180); return () => window.clearTimeout(timer); }, [filters]);
  const select = (key: keyof BloggerSearchFilters, value: string | number | undefined) => setFilters((current) => ({ ...current, [key]: value || undefined }));
  return <div className="screen space-y-4 px-4 pt-5"><header className="flex items-center justify-between"><div><p className="text-sm font-semibold text-brand-muted">{t("search.eyebrow")}</p><h1 className="mt-1 text-3xl font-extrabold tracking-tight">{t("search.title")}</h1></div><button aria-expanded={filtersOpen} aria-label={t("search.filters")} className="grid h-11 w-11 place-items-center rounded-2xl bg-white shadow-card" onClick={() => setFiltersOpen((value) => !value)} type="button"><Icon name="filter" /></button></header><SearchBar onChange={(event) => select("query", event.target.value)} placeholder={t("search.placeholder")} value={filters.query ?? ""} />
    <div className="no-scrollbar -mx-4 flex gap-2 overflow-x-auto px-4 pb-1"><button onClick={() => select("category", undefined)} type="button"><Chip active={!filters.category}>{t("common.all")}</Chip></button>{categories.slice(0, 8).map((category) => <button key={category} onClick={() => select("category", filters.category === category ? undefined : category)} type="button"><Chip active={filters.category === category}>{categoryLabel(category)}</Chip></button>)}</div>
    {filtersOpen && <section className="grid gap-3 rounded-3xl border border-brand-line bg-white p-4 shadow-card"><div className="grid grid-cols-2 gap-3"><FilterSelect label={t("common.city")} onChange={(value) => select("city", value)} options={[["", t("common.any")], ...uzbekistanRegions.map((city) => [city, cityLabel(city)])]} value={filters.city ?? ""} /><FilterSelect label={t("search.platform")} onChange={(value) => select("platform", value)} options={[["", t("common.all")], ["instagram", t("search.platformInstagram")], ["telegram", t("search.platformTelegram")], ["tiktok", t("search.platformTiktok")], ["youtube", t("search.platformYoutube")]]} value={filters.platform ?? ""} /><FilterSelect label={t("search.followers")} onChange={(value) => select("minFollowers", Number(value) || undefined)} options={[["", t("common.all")], ["10000", "10 000+"], ["50000", "50 000+"], ["100000", "100 000+"]]} value={String(filters.minFollowers ?? "")} /><FilterSelect label={t("search.er")} onChange={(value) => select("minEr", Number(value) || undefined)} options={[["", t("common.all")], ["3", "3%+"], ["5", "5%+"], ["8", "8%+"]]} value={String(filters.minEr ?? "")} /><FilterSelect label={t("search.maxPrice")} onChange={(value) => select("maxPrice", Number(value) || undefined)} options={[["", t("search.anyPrice")], ["300000", `${t("common.to")} 300 000`], ["500000", `${t("common.to")} 500 000`], ["1000000", `${t("common.to")} 1 000 000`]]} value={String(filters.maxPrice ?? "")} /><FilterSelect label={t("search.sort")} onChange={(value) => select("sort", value)} options={[["popular", t("search.sortPopular")], ["rating", t("search.sortRating")], ["er", t("search.sortEr")], ["price", t("search.sortPrice")], ["newest", t("search.sortNewest")]]} value={filters.sort ?? "popular"} /></div></section>}
    <p className="text-sm text-brand-muted">{loading ? t("search.loading") : t("search.found", { count: total })}</p><div className="grid gap-3">{loading ? [1, 2, 3].map((item) => <Skeleton className="h-48" key={item} />) : failed ? <div className="space-y-3"><EmptyState icon="filter" subtitle={t("search.loadFailedSubtitle")} title={t("search.loadFailedTitle")} /><Button className="w-full" onClick={load} type="button">{t("common.retry")}</Button></div> : bloggers.length ? bloggers.map((blogger) => <BloggerCard blogger={blogger} key={blogger.id} />) : <EmptyState subtitle={t("search.emptySubtitle")} title={t("search.emptyTitle")} />}</div><BottomNav /></div>;
}

function FilterSelect({ label, value, options, onChange }: { label: string; value: string; options: string[][]; onChange: (value: string) => void }) {
  return <label className="text-sm font-bold">{label}<select className="mt-1 h-11 w-full rounded-xl border border-brand-line bg-white px-3 font-normal" onChange={(event) => onChange(event.target.value)} value={value}>{options.map(([optionValue, optionLabel]) => <option key={optionValue} value={optionValue}>{optionLabel}</option>)}</select></label>;
}
